sudo: required
language: generic
services: docker

script:
  - docker run --rm -v $(pwd):/tex aergus/latex /bin/sh -c "cd /tex; latexmk -pdf main.tex"
  - mkdir -p ../public/
  - cp ./main.pdf ../public/ali_sorouramini.pdf

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
